/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "example/inc/led.h"
#include "example/inc/hsi.h"
#include "gpio.h"

// semi hosting init function
extern void initialise_monitor_handles(void);

int main(void)
{

	turnOnLED();
	meaHSI();
    /* Loop forever */
	for(;;);
}

void EXTI0_IRQHandler(void)
{
	// Handle the interrupt
	GPIO_irq_handle(0);
}