/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

// Turn ON the LED
// 1. Address of the Clock control register (AHB ENR)
// - 0x40021000 + 0x14 = 0x40021014
// 2. Address of the GPIO mode register (used to control mode)
// - LD1 -> PB0:  base: 0x48000400 + GPIOx_MODER: 0x0  (Set [1:0] to 0x01: General purpose output)
// - LD2 -> PB7:  base: 0x48000400 + GPIOx_MODER: 0x0  (Set [15:14] to 0x01: General purpose output)
// - LD3 -> PB14: base: 0x48000400 + GPIOx_MODER: 0x0  (Set [29:28] to 0x01: General purpose output)
// - LD7 -> PE11: base: 0x48001000 + GPIOx_MODER: 0x0  (Set [23:22] to 0x01: General purpose output)
// - LD8 -> PE14:
// 3. Address of the GPIO output data register (used to write)
// - LD1 -> PB0:  base: 0x48000400 + GPIOx_ODR: 0x14  (Set [0] to 0x01: Port output data)
// - LD2 -> PB7:  base: 0x48000400 + GPIOx_ODR: 0x14  (Set [7] to 0x01: Port output data)
// - LD3 -> PB14: base: 0x48000400 + GPIOx_ODR: 0x14  (Set [14] to 0x01: Port output data)
// - LD7 -> PE11: base: 0x48001000 + GPIOx_ODR: 0x14  (Set [11] to 0x01: Port output data)
// - LD8 -> PE14:

// semi hosting init function
extern void initialise_monitor_handles(void);

int main(void)
{
	uint32_t *pClkCtrlReg = (uint32_t *)0x40021014;
	uint32_t *pPBModeReg = (uint32_t *)0x48000400;
	uint32_t *pPBOutReg = (uint32_t *)0x48000414;

	uint32_t *pPEModeReg = (uint32_t *)0x48001000;
	uint32_t *pPEOutReg = (uint32_t *)0x48001014;

	// 1. Enable the clock for GPIOB peripheral in the AHBENR
	uint32_t temp = *pClkCtrlReg;	// Read operation
	temp = temp | (0x1 << 18) | (0x1 << 21);		// Modify
	*pClkCtrlReg = temp;	// Write back

	// 2. Configure the mode of IO pin as output
	uint32_t temp2 = *pPBModeReg;
	temp2 = temp2 | (0x1 << 0) | (0x1 << 14) | (0x1 << 28);
	*pPBModeReg = temp2;

	// -----
	*pPEModeReg |= (0x1 << 22) | (0x1 << 28);

	// 3. Set output data register to make I/O pin as HIGH
	uint32_t temp3 = *pPBOutReg;
	temp3 = temp3 | (0x1 << 0) | (0x1 << 7) | (0x1 << 14);
	*pPBOutReg = temp3;

	// -----
	*pPEOutReg |= (0x1 << 11) | (0x1 << 14);

    /* Loop forever */
	for(;;);
}