/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <string.h>

#include "example/inc/led.h"
#include "example/inc/hsi.h"
#include "example/inc/btn_interrupt.h"
#include "example/inc/spi_ex.h"

// semi hosting init function
extern void initialise_monitor_handles(void);

int main(void)
{
	// btn_interrupt();
	// turnOnLED();
	// meaHSI();
    /* Loop forever */

	// /** 
	//  * SPI example
	//  */
	char usr_data[] = "Hello world";
	SPI3_gpio_init();
	SPI3_init();
	// Make NSS signal internally high, otherwise, trigger mode faule (MODF)
	SPI_ssi_config((SPI_I2S_REG_T *)SPI3_I2S3_BASEADDR, 1);
	// Before sending the data, Enable the SPI3 peripheral
	SPI_peri_ctrl((SPI_I2S_REG_T *)SPI3_I2S3_BASEADDR, 1);
	// Send data
	SPI_send((SPI_I2S_REG_T *)SPI3_I2S3_BASEADDR, (uint8_t *)usr_data, strlen(usr_data));

	for(;;);
}

void EXTI0_IRQHandler(void)
{
	// Handle the interrupt
	GPIO_irq_handle(0);
}